apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: nt135
spec:
  environments:
    default:
      defaultNamespace: default
      server: https://51.250.70.171:6443
    stage:
      defaultNamespace: stage
      server: https://51.250.70.171:6443
    production:
      defaultNamespace: production
      server: https://51.250.70.171:6443
      includes:
        - endp
  vars: {}
  excludes:
    - endp