---
apiVersion: v1
kind: Service
metadata:
  name: pma-service
spec:
  type: LoadBalancer
  loadBalancerIP: 37.18.100.189
  selector:
    app: pma
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
