---
apiVersion: v1
kind: Pod
metadata:
  labels:
    role: module1
    project: myproject
  name: module1
spec:
  containers:
    - image: wbitt/network-multitool:alpine-extra
      imagePullPolicy: IfNotPresent
      name: module1
      env:
        - name: HTTP_PORT
          value: "5978"
  terminationGracePeriodSeconds: 30

