---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault
  name: vault
spec:
  type: ClusterIP
  ports:
  - name: vault
    port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app: vault
