apiVersion: v1
kind: PersistentVolume
metadata:
  name: atlantis-data
spec:
  capacity:
    storage: 5Gi
  # claimRef:
  #   name: atlantis-data
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Recycle
  hostPath: 
    path: /data/diploma