---
- name: Create instance
  hosts: localhost
  tasks:
    - name: "Create {{ homework }}-vm1"
      netology86.yandex_cloud_elk.yc_create_instance:
        network_interface: "net-ru-central1-a"
        name: "{{ homework }}-vm1"
        # image_family: "centos-stream-8"
        image_family: "ubuntu-2004-lts"
        cores: 2
        memory: 4
        status: "running"

    - name: Refresh Inventory
      meta: refresh_inventory

- name: Add new host to inventory
  hosts: all
  gather_facts: false
  user: yc-user
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 100

- name: Install Docker on nodes
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Installing necessary packages
      apt: >
          name={{ item }}
          state=present
          update_cache=yes
      with_items:
          - conntrack
          - docker.io

- name: Install and run Kuber
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Get kube version
      uri:
        url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
        return_content: yes
      register: kube_version
    - name: Download kubectl
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/{{ kube_version.content }}/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
    - name: Download minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Check Kuber version
      command: minikube version
      register: check_minikube_version
    - name: Print minikube version
      debug: 
        var: check_minikube_version.stdout_lines

    - name: Run minikube
      command: 
        cmd: minikube start --vm-driver=none

    - name: Get minikube status
      command: 
        cmd: minikube status
      register: get_minikube_status
    - name: Print minikube status
      debug:
        var: get_minikube_status.stdout_lines

    - name: Get kubectl pods
      command: 
        cmd: kubectl get pods --namespace=kube-system
      register: get_pods
    - name: Print kubectl pods
      debug:
        var: get_pods.stdout_lines

