---
- name: Create instance
  hosts: localhost
  roles:
    - create-vm

- name: Wait for instance to become available
  hosts: all
  gather_facts: false
  user: yc-user
  roles:
    - wait-vm

- name: Run hello node in minikube
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - install-kuber
    - run-kuber
