version: '3.6'

volumes:
  es_hot_data:
  es_warm_data:

configs:
  filebat-config:
    name: "filebat-config"
    file: ./filebeat.docker.yml

networks:
  elk:
    driver: bridge

services:
  es-hot:
    image: elasticsearch:7.17.2
    container_name: es-hot
    environment:
      - node.name=es-hot
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es-hot
      - cluster.initial_master_nodes=es-hot
      # - cluster.initial_master_nodes=es-hot,es-warm
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    # deploy:
    #   resources:
    #     limits:
    #       memory: 500M
        # reservations:
        #   memory: 500M
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_hot_data:/usr/share/elasticsearch/data
      - "./jvm.options:/usr/share/elasticsearch/config/jvm.options.d/jvm.options"
    expose:
      - "9200"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
  es-warm:
    image: elasticsearch:7.17.2
    container_name: es-warm
    environment:
      - node.name=es_warm
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es-warm
      - cluster.initial_master_nodes=es-hot,es-warm
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms96m -Xmx96m"
    # deploy:
    #   resources:
    #     limits:
    #       memory: 250M
    #     reservations:
    #       memory: 250M
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_warm_data:/usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9201:9200"
      - "9301:9300"
    networks:
      - elk

  logstash:
    image: logstash:7.17.2
    container_name: logstash
    environment:
      - "ES_JAVA_OPTS=-Xms96m -Xmx96m"
    # deploy:
    #   resources:
    #     limits:
    #       memory: 250M
    #     reservations:
    #       memory: 250M
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
    expose:
      - "5044"
    ports:
      - "5044:5044"
    networks:
      - elk

  kibana:
    image: kibana:7.17.2
    container_name: kibana
    # deploy:
    #   resources:
    #     limits:
    #       memory: 500M
        # reservations:
        #   memory: 250M
    environment:
      - "SERVER_NAME=kibana"
      - "SERVER_HOST=0.0.0.0"
      - "ELASTICSEARCH_HOSTS=http://es-hot:9200"
      - "NODE_OPTIONS=--max-old-space-size=4096"
      - "ES_JAVA_OPTS=-Xms96m -Xmx96m"
    volumes:
      - "./node.options:/opt/kibana/config/node.options"
    expose:
      - "5601"
    ports:
      - "5601:5601"
    networks:
      - elk

  filebeat:
    image: elastic/filebeat:7.17.2
    container_name: filebeat
    # configs:
    #   - source: filebat-config
    #     target: /usr/share/filebeat/filebeat.yml
    #     uid: "1000"
    #     gid: "1000"
    #     mode: 0644
    # user: root
    privileged: true
    command:
      - "--strict.perms=false"
    # environment:
    #   - output.logstash.hosts: "localhost:5044"
      # - strict.perms=false
    user: root
    volumes:
      - "./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:Z"
    # expose:
    # ports:
    networks:
      - elk