services:
  jenkins:
    image: jenkins-with-plugins
    # image: jenkins/jenkins:2.361.2-lts-jdk11
    # user: root
    # --group-add=$(stat -c %g /var/run/docker.sock)
    # group_add:
    #   - 1001
    privileged: true
    ports:
      - 8090:8080
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      # - A=B
    volumes:
      - ./data:/var/jenkins_home
      - ./jobs:/var/jenkins_home/jobs
      - ./credentials.xml:/var/jenkins_home/credentials.xml
      - /var/run/docker.sock:/var/run/docker.sock
