apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nt131-back
  name: nt131-back
  namespace: prod
spec:
  selector:
    matchLabels:
      app: nt131-back
  replicas: 1
  template:
    metadata:
      labels:
        app: nt131-back
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:13-alpine
        command: [ "sh", "-c", "until pg_isready -h db -p 5432 -U postgres:postgres; do echo 'not yet'; sleep 2; done" ]
      containers:
      - image: runout/13-kubernetes-config_backend:latest
        imagePullPolicy: IfNotPresent
        name: backend
        resources:
          requests:
            memory: "1000Mi"
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@db:5432/news
        volumeMounts:
          - mountPath: "/data/static"
            name: static-storage
      volumes:
        - name: static-storage
          persistentVolumeClaim:
            claimName: static-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nt131-back
  name: nt131-back
  namespace: prod
spec:
  type: ClusterIP
  ports:
  - name: nt131-back
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: nt131-back
