apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nt132
  name: nt132
  namespace: stage
spec:
  selector:
    matchLabels:
      app: nt132
  replicas: 1
  template:
    metadata:
      labels:
        app: nt132
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:13-alpine
        command: [ "sh", "-c", "until pg_isready -h db -p 5432 -U postgres:postgres; do echo 'not yet'; sleep 2; done" ]
      containers:
      - image: runout/13-kubernetes-config_backend:latest
        imagePullPolicy: IfNotPresent
        name: backend
        volumeMounts:
          - mountPath: "/stata/static"
            name: static-storage
      - image: runout/13-kubernetes-config_frontend:latest
        imagePullPolicy: IfNotPresent
        name: frontend
        volumeMounts:
          - mountPath: "/data/cache"
            name: static-storage
      volumes:
      - name: static-storage
        emptyDir: {}