{{- $namespace := .Values.global.namespace }}
{{- if  .Values.global.persistence.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-storage-pvc
  namespace: {{ $namespace }}
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{  .Values.global.persistence.storage_size }}
{{ end }}