apiVersion: v2
name: nt134
description: Netology devops course homework 13.4
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1

# Application info
home: https://github.com/run0ut/devops-netology/blob/main/04-devkub-homeworks/13-kubernetes-config-04-helm.md
sources: 
  - https://github.com/run0ut/devops-netology/tree/main/04-devkub-homeworks/13-kubernetes-config-04-helm
icon: https://netology.ru/favicon-16x16.png
appVersion: "1.0.0"

dependencies:
  - name: nfs-subdir-external-provisioner
    version: ~4.0.16
    repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    condition: global.persistence.enabled
    alias: nfs-client