---
- name: Get kuber credentials
  hosts: "{{ hw_index }}-control-0"
  become: yes
  gather_facts: yes
  tasks:
    - name: Save host to var
      set_fact:
        kube_control_node: "{{ ansible_host }}"
    - name: Print fact
      debug:
        var: kube_control_node

    - name: Duplicate folder kube
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /etc/kubernetes/admin_export.conf
        remote_src: yes
        mode: 0600

    - name: Set Kube IP in config
      replace:
        path: /etc/kubernetes/admin_export.conf
        regexp: 'server: https://[0-9.]*:'
        replace: "server: https://{{ kube_control_node }}:"
    - name: Fetch kube config
      synchronize:
        src: /etc/kubernetes/admin_export.conf
        dest: ~/.kube/config
        delete: yes
        recursive: yes
        owner: no
        group: no
        mode: pull

    - name: check namespace stage
      shell:
        cmd: kubectl get namespaces  | grep '^stage.*Active'
      register: stage_ns_exists
      changed_when: false
      failed_when: false
    - name: create namespace stage
      shell:
        cmd: kubectl create namespace stage
      when: stage_ns_exists.rc != 0

    - name: check namespace prod
      shell:
        cmd: kubectl get namespaces  | grep '^prod.*Active'
      register: prod_ns_exists
      changed_when: false
      failed_when: false
    - name: create namespace prod
      shell:
        cmd: kubectl create namespace prod
      when: prod_ns_exists.rc != 0
