---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nt131-front
  name: nt131-front
  namespace: prod
spec:
  type: ClusterIP
  ports:
  - name: nt131-front
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nt131-front