---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  vault.json: |-
    {
        "listener": {
          "tcp": {
            "address": "0.0.0.0:8200",
            "tls_disable": 1
          }
        },
        "storage": {
          "file": {
            "path": "/vault/secrets"
          }
        },
        "ui": true,
        "log_level": "debug"
    }
