apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db 
  namespace: prod
spec:  
  selector:
    matchLabels:
      app: db
  serviceName: "db"
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:13-alpine
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: news
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: prod
spec:
  type: ClusterIP
  ports:
  - name: db
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: db